# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-29 01:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20180628_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.FileField(upload_to='images'),
        ),
    ]
