# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-04 16:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20180629_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.CharField(default=' ', max_length=255),
            preserve_default=False,
        ),
    ]
