# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-28 17:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_remove_orderproductlist_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='billing_address_1',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='order',
            name='billing_address_2',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='order',
            name='billing_city',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='order',
            name='billing_state',
            field=models.CharField(default='', max_length=2),
        ),
        migrations.AddField(
            model_name='order',
            name='billing_zip',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='cc_exp_month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='cc_exp_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='cc_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='cc_security_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_address_1',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_address_2',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_city',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_state',
            field=models.CharField(default='', max_length=2),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_zip',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
