# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-27 21:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_auto_20180626_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='billing_address_2',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='shipping_address_2',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
