# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-27 21:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_auto_20180627_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='billing_first_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='billing_last_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='shipping_first_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='shipping_last_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
