# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-27 21:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_auto_20180627_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='billing_address_1',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='billing_city',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='billing_state',
            field=models.CharField(default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='user',
            name='billing_zip',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='cc_exp_month',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='cc_exp_year',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='cc_number',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='cc_security_code',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='shipping_address_1',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='shipping_city',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='shipping_state',
            field=models.CharField(default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='user',
            name='shipping_zip',
            field=models.IntegerField(default=''),
        ),
    ]
