# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-27 22:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_auto_20180627_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='billing_address_1',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='billing_address_2',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='billing_city',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='shipping_address_1',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='shipping_address_2',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='shipping_city',
            field=models.TextField(default=''),
        ),
    ]
