# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-28 17:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0008_auto_20180627_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='billing_zip',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='cc_exp_month',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='cc_exp_year',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='cc_number',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='cc_security_code',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='shipping_zip',
            field=models.IntegerField(blank=True),
        ),
    ]
